version: '2'
services:
  moodledb_rpi:
    image: arm32v7/postgres:11
    container_name: moodledb_rpi
    environment:
    # MAKE SURE THIS ONE SAME WITH THE MOODLE
    - POSTGRES_DATABASE=moodle
    - POSTGRES_USER=moodle
    - POSTGRES_PASSWORD=moodle
  moodle_rpi:
    image: treehouses/moodle:rpi-latest
    container_name: moodle_rpi
    ports:
      - "80:80"
    environment:
    - NGINX_PORT=80
    - MOODOLE_DB_URL=moodledb_rpi
    - MOODOLE_DB_NAME=moodle
    - MOODOLE_DB_USER=moodle
    - MOODOLE_DB_PASS=moodle
    - MOODOLE_DB_PORT=5432
    - MOODOLE_MAX_BODY_SIZE=200M
    - MOODOLE_BODY_TIMEOUT=300s
