version: '2'
services:
  moodledb_rpi_alpine:
    image: arm32v7/postgres
    container_name: moodledb_rpi_alpine
    environment:
    # MAKE SURE THIS ONE SAME WITH THE MOODLE
    - POSTGRES_DATABASE=moodle
    - POSTGRES_USER=moodle
    - POSTGRES_PASSWORD=moodle
  moodle_rpi_alpine:
    image: lilyxxx/moodole:pi-01
    container_name: moodle_rpi_alpine
    ports:
      - "80:80"
    environment:
    - NGINX_PORT=80
    - MOODOLE_DB_URL=moodledb_rpi_alpine
    - MOODOLE_DB_NAME=moodle
    - MOODOLE_DB_USER=moodle
    - MOODOLE_DB_PASS=moodle
    - MOODOLE_DB_PORT=5432
    - MOODOLE_MAX_BODY_SIZE=200M
    - MOODOLE_BODY_TIMEOUT=300s
